# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss', '0003_auto_20170525_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('feed_link', models.URLField(max_length=300)),
                ('published_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedWebsite',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_feed_url', models.URLField(max_length=300)),
                ('website_url', models.URLField(max_length=300)),
                ('website_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_FeedWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.FeedWebsite')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Feeds',
        ),
        migrations.AddField(
            model_name='feeddetail',
            name='feed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.FeedWebsite'),
        ),
    ]
