# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_auto_20170614_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedwebsite',
            name='last_updated_on',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
