# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_feedwebsite_last_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeddetail',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feeddetail',
            name='feed_link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feeddetail',
            name='published_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='feeddetail',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedwebsite',
            name='last_updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='feedwebsite',
            name='website_feed_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feedwebsite',
            name='website_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedwebsite',
            name='website_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
