# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0007_auto_20170617_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeddetail',
            name='feed_id',
        ),
        migrations.AddField(
            model_name='feeddetail',
            name='feed_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rss.FeedWebsite'),
        ),
    ]
