# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0008_auto_20170617_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeddetail',
            name='feed_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedW_feedD', to='rss.FeedWebsite'),
        ),
    ]
