# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0009_auto_20170617_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_feedwebsite',
            name='feed_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rss.FeedWebsite'),
        ),
        migrations.AlterField(
            model_name='user_feedwebsite',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
