# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0013_auto_20170617_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeddetail',
            name='published_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feedwebsite',
            name='last_updated_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
